export const slots = [
  // reservation-enabled slots: some free, some reserved
  { id: 'P1', status: 'inactive', schedule: { '10:00': 'Reserved' }, isReservationSlot: true, isReserved: false },
  { id: 'P2', status: 'inactive', schedule: { '09:00': 'Reserved' }, isReservationSlot: true, isReserved: true },
  { id: 'P3', status: 'reserved not checked in', schedule: { '08:00': 'Reserved not checked in' }, isReservationSlot: true, isReserved: true },
  { id: 'P4', status: 'inactive', isReservationSlot: true, isReserved: false },
  { id: 'P5', status: 'inactive', isReservationSlot: true, isReserved: false },
  { id: 'P6', status: 'reserved', schedule: { '10:00': 'Reserved' }, isReservationSlot: true, isReserved: true },
  { id: 'P7', status: 'reserved', schedule: { '12:00': 'Reserved not checked in' }, isReservationSlot: true, isReserved: true },
  { id: 'P8', status: 'reserved', isReservationSlot: true, isReserved: true },
  { id: 'P9', status: 'inactive', isReservationSlot: true, isReserved: false },
  { id: 'P10', status: 'inactive', isReservationSlot: true, isReserved: false },
  // offline (not reservation-enabled) — make some occupied to simulate valet offline assigns
  { id: 'P11', status: 'inactive', assignedReservationId: 'OFF-1001' },
  { id: 'P12', status: 'inactive' },
  { id: 'P13', status: 'overstay', schedule: { '08:00': 'Overstay', '09:00': 'Overstay' } },
  { id: 'P14', status: 'overstay' },
  { id: 'P15', status: 'inactive' },
  { id: 'P16', status: 'inactive' },
  { id: 'P17', status: 'reserved not checked in'},
  { id: 'P18', status: 'reserved not checked in'},
  { id: 'P19', status: 'inactive' },
  { id: 'P20', status: 'inactive' },
  { id: 'P21', status: 'inactive' },
  { id: 'P22', status: 'inactive' },
  { id: 'P23', status: 'reserved', assignedReservationId: 'OFF-1002' },
  { id: 'P24', status: 'reserved', assignedReservationId: 'OFF-1003' },
  { id: 'P25', status: 'inactive' },
  { id: 'P26', status: 'overstay' },
  { id: 'P27', status: 'overstay' },
  { id: 'P28', status: 'inactive' },
  { id: 'P29', status: 'inactive' },
  { id: 'P30', status: 'inactive' },
  { id: 'P31', status: 'inactive' },
  { id: 'P32', status: 'inactive' },
  { id: 'P33', status: 'inactive' },
  { id: 'P34', status: 'inactive' },
  { id: 'P35', status: 'inactive' },
  { id: 'P36', status: 'inactive' },
  { id: 'P37', status: 'inactive' },
  { id: 'P38', status: 'inactive' },
  { id: 'P39', status: 'inactive' },
  { id: 'P40', status: 'inactive' },
];
